name: Build and Release Signed APK

on:
  release:
    types: [created] # 仅在创建新 Release 时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > app/keystore.jks
      # 解码 Secrets 中的 keystore 文件

    - name: Build Signed Release APK
      run: |
        ./gradlew assembleRelease \
          -PstoreFile=keystore.jks \
          -PstorePassword=${{ secrets.KEYSTORE_PASSWORD }} \
          -PkeyAlias=${{ secrets.KEY_ALIAS }} \
          -PkeyPassword=${{ secrets.KEY_PASSWORD }}
      # 通过命令行参数传递签名信息给 Gradle
      # 注意：你项目的 app/build.gradle 中需要配置好 signingConfigs 使用这些参数

    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub 自动提供的 token
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: app/build/outputs/apk/release/app-release.apk
        asset_name: MyApp-${{ github.event.release.tag_name }}.apk
        asset_content_type: application/vnd.android.package-archive
